#----------------------
# About section

blurb: <p><strong> Neuroeconomics </strong> I am a researcher in the interdisciplinary field of economics, management science, neuroscience and psychology </p>

#---------------------- 
# Courses section
courses:
  - {title: R language and data analysis, semester: Fall 2015, school: Zhejiang University of Technology, description: A course for R and data analysis, link: courses/temp_course }
  - {title: R language and data analysis, semester: Fall 2016, school: Zhejiang University, description: A course for R and data analysis, link: courses/temp_course }
  - {title: R language and data analysis, semester: Fall 2016, school: Zhejiang University, description: A course for R and data analysis, link: courses/temp_course }
#----------------------
# Contact
contact-info: <p>Qiang Shen (沈强)<br>Zhejiang University of Technology<br>Department of Business Adminstration<br>Strand<br>Hangzhou<br>WC2R 2LS<br>China</p>

contact-links:
  - {contact-text: Github, contact-link: "https://www.google.com", icon: 'favicon.html'}
